"""Add location fields to Field model

Revision ID: add_location_fields
Revises: 
- Add location, city, latitude, longitude fields to Field model

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_location_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('field', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('field', sa.Column('longitude', sa.Float(), nullable=True))
    # end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'longitude')
    op.drop_column('field', 'latitude')
    op.drop_column('field', 'city')
    # end Alembic commands ###
