"""Remove unique constraint from staff.email

Revision ID: remove_staff_email_unique
Revises: add_location_fields
Create Date: 2026-01-04 20:48:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision = 'remove_staff_email_unique'
down_revision = 'add_location_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to recreate table without unique constraint
    op.execute('CREATE TABLE staff_new AS SELECT * FROM staff')
    op.drop_table('staff')
    op.create_table('staff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('position', sa.String(length=50), nullable=False),
        sa.Column('hire_date', sa.Date(), nullable=True),
        sa.Column('salary', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('field_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['field_id'], ['field.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute('INSERT INTO staff SELECT * FROM staff_new')
    op.drop_table('staff_new')
    # end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to recreate table with unique constraint
    op.execute('CREATE TABLE staff_new AS SELECT * FROM staff')
    op.drop_table('staff')
    op.create_table('staff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('position', sa.String(length=50), nullable=False),
        sa.Column('hire_date', sa.Date(), nullable=True),
        sa.Column('salary', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('field_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['field_id'], ['field.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.execute('INSERT INTO staff SELECT * FROM staff_new')
    op.drop_table('staff_new')
    # end Alembic commands ###
